Add item requests and gateway
ardivad2015/java-shareit pull request #3
Opened 2024-12-03 20:36 UTC by ardivad2015

2024-12-04 17:39 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшую рекомендацию

2024-12-04 17:39 UTC, mikita95 commented on server/src/main/resources/schema.sql
> +         author_id bigint NOT NULL,
Можно было бы добавить индексы на колонки по которым часто выполняются запросы так было бы эффективнее

2024-12-04 20:20 UTC, ardivad2015 commented on server/src/main/resources/schema.sql
> +         author_id bigint NOT NULL,
На первичный ключ же по умолчанию создаётся, а для author_id в 17 строке создание индекса.

2024-12-06 06:50 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-12-06 06:51 UTC, mikita95 commented on server/src/main/resources/schema.sql
> +         author_id bigint NOT NULL,
Ох, точно! Прошу прощения, все отлично :)

2024-12-06 19:38 UTC, merged